//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivityMain()
        {
            this.ActivityTimeRate = new HashSet<ActivityTimeRate>();
        }
    
        public int id { get; set; }
        public int IdEventName { get; set; }
        public int IdWinner { get; set; }
        public System.DateTime DateStart { get; set; }
        public int CountOfDay { get; set; }
    
        public virtual EventName EventName { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityTimeRate> ActivityTimeRate { get; set; }
    }
}
