//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int id { get; set; }
        public int IdEventName { get; set; }
        public int IdDirectionEvent { get; set; }
        public System.DateTime Date { get; set; }
        public int Days { get; set; }
        public int IdCity { get; set; }
        public byte[] EventImage { get; set; }
    
        public virtual City City { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual EventName EventName { get; set; }
    }
}
