//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.ActivityMain = new HashSet<ActivityMain>();
            this.ActivityTimeRate = new HashSet<ActivityTimeRate>();
            this.ActivityTimeRate1 = new HashSet<ActivityTimeRate>();
            this.ActivityTimeRate2 = new HashSet<ActivityTimeRate>();
            this.ActivityTimeRate3 = new HashSet<ActivityTimeRate>();
            this.ActivityTimeRate4 = new HashSet<ActivityTimeRate>();
            this.ActivityTimeRate5 = new HashSet<ActivityTimeRate>();
        }
    
        public int id { get; set; }
        public string Familiy { get; set; }
        public string Name { get; set; }
        public string Otchestvo { get; set; }
        public int IdRole { get; set; }
        public int IdPol { get; set; }
        public string Mail { get; set; }
        public System.DateTime BirthdayDate { get; set; }
        public Nullable<int> IdCountry { get; set; }
        public string NumberPhone { get; set; }
        public Nullable<int> IdDirection { get; set; }
        public Nullable<int> IdUserEvent { get; set; }
        public string Password { get; set; }
        public string PhotoName { get; set; }
        public string UserPhoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityMain> ActivityMain { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityTimeRate> ActivityTimeRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityTimeRate> ActivityTimeRate1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityTimeRate> ActivityTimeRate2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityTimeRate> ActivityTimeRate3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityTimeRate> ActivityTimeRate4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityTimeRate> ActivityTimeRate5 { get; set; }
        public virtual Country Country { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual UserEvent UserEvent { get; set; }
        public virtual UserGender UserGender { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
